<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <KSP_DIR Condition="'$(KSP_DIR)' == ''">C:\Program Files\Epic Games\KerbalSpaceProgram\KerbalSpaceProgram</KSP_DIR>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" Version="18.3.36812.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VirtualCameraRecorder\VirtualCameraRecorder.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(KSP_DIR)\KSP_x64_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(KSP_DIR)\KSP_x64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(KSP_DIR)\KSP_x64_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="UnityEngine.RenderingModule">
      <HintPath>$(KSP_DIR)\KSP_x64_Data\Managed\UnityEngine.RenderingModule.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(KSP_DIR)\KSP_x64_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(KSP_DIR)\KSP_x64_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
</Project>
